---
- hosts: all

  tasks:
  - name: Install Maven using YUM.
    yum:
      name: "maven"
      state: latest  
    become: true
  - name: Maven wrapper
    command: mvn -N io.takari:maven:wrapper
    args:
      chdir: /var/www/springpetclinc/
