---
- hosts: all

  tasks:
  - name: Start Spring Pet Clinic
    shell: “./mvnw package”
  - name: Start Spring Pet Clinic
    shell: “java -jar target/*.jar”
    args:
      chdir: “/var/www/springpetclinic”
